spring:
  application:
    name: wxshop-orderservice
  datasource:
    url: jdbc:mysql://localhost:3307/order?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

mybatis:
  config-location: classpath:db/mybatis/config.xml

dubbo:
  scan:
    base-packages: com.huan.order.service
  # Dubbo Protocol
  protocol:
    name: dubbo
    ## Random port
    port: -1
  ## Dubbo Registry
  registry:
    address: zookeeper://127.0.0.1:2181

server:
  port: 8081

wxshop:
  orderservice:
    version: 1.0.1